### ISSUE TITLE
Plugin name in manifest should be cleaned up to avoid clutter in the library

### ISSUE THREAD

**Issue by david-c14** [david-c14/SubmarineFree#102]
As per guidelines from Andrew.

**Comment by david-c14** [comment]
@AndrewBelt I have removed (free) from plugin name in manifest as you recommended

**Comment by AndrewBelt** [comment]
Make sure the version is bumped and request a VCV Library update. https://github.com/VCVRack/library#adding-your-plugin-to-the-vcv-library-for-open-source-plugins
