### ISSUE TITLE
no link in the index page to the new storage scope

### ISSUE THREAD

**Issue by squinkylabs** [david-c14/SubmarineFree#110]
There is nice documentation if you find the .md file yourself, but from the main index there is no link to this new manual. Looks like an excellent module, btw.

**Comment by david-c14** [comment]
Are you sure its missing? Its there in github. On the index.MD between FF and LA.  Is it missing from the vcv library release.

**Comment by squinkylabs** [comment]
It's certainly there now, so probably I was wrong before.

**Comment by david-c14** [comment]
No problem. Thanks for letting me know
