### ISSUE TITLE
More features for HS please!

### ISSUE THREAD

**Issue by squinkylabs** [david-c14/SubmarineFree#126]
What a nice scope! Perhaps I'm missing it (again), but there are some features I would really like:

1) Trigger from input. It's nice to have separate trigger input, but being able to trigger from the main input would be nice Preferable with a selectable trigger level like the VCV scope. This would make it usable as a "regular" scope.

2) One shot mode. When using an external trigger I would like the ability to trigger once and store, even it the trigger input is (for example) a repeating clock.

3) shorter minimum time. 1/16 of a second isn't all that fast. Ability to go up to one sample per pixel (or event more) would be very nice. Of course the zoom command does the job nicely.

**Comment by david-c14** [comment]
1. You could wire the signal to both the input and the trigger.


3. I don't understand what you mean. It always records every sample. And one sample per pixel is meaningless, because it would be very odd if the scope changed its behaviour if you change the overall zoom in rack.

**Comment by david-c14** [comment]
W. Is a possibility. I didn't envisage anyone trying to use it as a live scope. It doesn't display while sampling. So I would have no qualms with passing the trigger through something like an LD-106 to control the trigger level, and passing the input through a delay such as an unclocked BB-120 to compensate.

**Comment by squinkylabs** [comment]
1) wiring input to trigger is pretty clever - would be a good thing to put in the manual. Of course it still doesn't have a nice UI for setting the trigger level, like VCV scope.

3) I want to see individual samples without zooming. I'll settle for a fastest sweep of better than 1/16 of a second. how about 1/1000 of a second?

2) I guess I wasn't thinking of that as a "live" feature. I just want to grab a properly triggered frame, look at it, then grab another.

btw, I think all of these things are normal features of "real" oscilloscopes.

**Comment by david-c14** [comment]
I'll think about what can be done.

The shorter sweep time is tricky.  Not that it's tricky to implement, but the number of samples in a sweep depends on the engine sample rate, and the number of samples per pixel depends on the rack zoom level (as well as the module zoom control). There's no easy way to implement an automatic 1:1 zoom level.

But reducing the minimum length of sweep to 1/1000 (probably 1/1024) should be fine.

**Comment by david-c14** [comment]
version 1.1.7 has reduced the minimum time-base to 1/1000 second

**Comment by squinkylabs** [comment]
just using it now. It's SO good
![image](https://user-images.githubusercontent.com/16314838/89108084-b161b500-d3ea-11ea-86ac-be953b317389.png)
