### ISSUE TITLE
BP-102 Behavior

### ISSUE THREAD

**Issue by Telerex** [david-c14/SubmarineFree#127]
Just to let you know that the blank panel BP-102's center turns black when partly off the top of the screen and can only be dragged by it's outer edge as if it were a TD-202. This is on Windows 10, if that helps.
Still using it though.....Thanks

**Comment by david-c14** [comment]
This is definitely wrong, and I looks like its been wrong for two years. I'm surprised it doesn't do it more often. Thanks.

**Comment by smok-e** [comment]
just today I found the same bug ;-)
