### ISSUE TITLE
request: extended PO-204

### ISSUE THREAD

**Issue by glocke01** [david-c14/SubmarineFree#138]
I'd like to see a version of PO-204 with an additional knob and additional jack per "operator":

- knob: an attenuator on the phase input
- jack: VCA controlling the amount of phase modulation

**Comment by david-c14** [comment]
It was designed to be used with other devices, rather than being a whole synth on its own. I recommend an external adsr and vca or attenuator.

**Comment by david-c14** [comment]
That might have sounded a bit harsh. I'll consider it.

**Comment by david-c14** [comment]
Added EN-104 instead.

I believe that modular devices are best being modular. I don't want to overcomplicate individual modules.
