### ISSUE TITLE
TD-410 width expands to overlap adjacent module

### ISSUE THREAD

**Issue by typicalanalytical** [david-c14/SubmarineFree#141]
![2020-09-05 07_08_10-VCV Rack v1 1 6 - _Sequence video redo from scratch 2 (includes sound changes) v](https://user-images.githubusercontent.com/30984809/92303833-b1ebef00-ef46-11ea-89ef-a59a21cd6961.png)

**Comment by david-c14** [comment]
I can't reproduce this problem.   Do you have any step-by-step instructions that can reproduce the issue?

**Comment by david-c14** [comment]
Scratch that, I have been able to reproduce it now.  I'll work on a fix now.

**Comment by david-c14** [comment]
Fixed in v1.1.7
