### ISSUE TITLE
EN-104: Outputs 2-4 carrying signal of Input 1

### ISSUE THREAD

**Issue by anlexmatos** [david-c14/SubmarineFree#145]
I'm getting Input 1 normalled to all outputs even when all inputs are patched:

![image](https://user-images.githubusercontent.com/12039110/92921318-d857d180-f401-11ea-96d5-e46ecc18ca55.png)

Windows 7, Rack v1.1.6

**Comment by david-c14** [comment]
Sorry. Definitely a bug. Will fix asap
