### ISSUE TITLE
LA-108 outputs

### ISSUE THREAD

**Issue by unlessgames** [david-c14/SubmarineFree#150]
Hey! 

Thank you for this collection! I really like the cable color matching and multiple rows on this scope but one thing I'd find useful is to have outputs at the end of each row that just copy what gets patched to the inputs. By inserting these in the patch in a "permanent" fashion, I think this would help with creating patches that are easier to read.

**Comment by david-c14** [comment]
I couldn't fit those in without making the device larger, and that's a breaking change for existing patches.

Also it would take additional processing to copy the inputs to the outputs, not much, but it seems overkill.  I can't think of many other devices that do anything similar.

I'm just not convinced of the benefits.   I won't dismiss it straight away.  I'll keep thinking.

I like your modules also by the way, particularly atoms.

**Comment by unlessgames** [comment]
You are absolutely right about the objections, I guess this is more an idea stemming from your module rather than a direct feature request for it. I'll think about it a bit more too, maybe formalizing it as a separate "visual declutter/patchbay" module is the way to go.

Thanks!

**Comment by david-c14** [comment]
I'm afraid I've decided that I definitely won't be doing this.

I think cable clutter is an issue all over rack, but I can't fit this into the module without making it a breaking change.
