### ISSUE TITLE
WM-102 Failed to create a preview in the module browser

### ISSUE THREAD

**Issue by NoxyNixie** [david-c14/SubmarineFree#157]
![image](https://user-images.githubusercontent.com/211381/100969856-131a6300-3534-11eb-8d42-5a9d9412cecb.png)

It is the only module (of the 2170 loaded) that failed to make a preview. The module itself works fine though and WM-101 shows my wire colors in the module browser just fine. (I've not tried a restart yet since it takes a while to load all the modules while scrolling :P )

**Comment by david-c14** [comment]
Thanks, I only found this issue myself on Monday.  It's fixed in version 1.1.10, should be released before the end of the year.

**Comment by NoxyNixie** [comment]
Awesome ;)
