### ISSUE TITLE
Trying to load any Submarine module crashes Rack

### ISSUE THREAD

**Issue by aaronalt** [david-c14/SubmarineFree#159]
### Details

Operating system and version: MacOS Mojave v.10.14.6
VCV Rack version: (1.1.5)
CPU: Macbook Pro (15-inch, 2019), 2.6 GHz Intel Core i7, 16 GB 2400 MHz DDR4, Intel UHD Graphics 630 1536 MB
Interface: MOTU Audio Express

### Summary
VCV Rack crashes when trying to load a SubmarineFree module, or when trying to load a group of modules with a tag that includes a SubmarineFree module.

### Steps to reproduce

- Subscribe to all modules through VCV Library
- Open VCV Rack 1.1.5, update latest Submarine modules, then restart Rack
- Right-click and filter tags by Brand, click Submarine - Rack crashes without loading
- Alternatively, repeat last step by trying to filter by module category, any one from this list: 
mixer, digital, dual, envelope generator, hardware clone, logic, multiple, noise, oscillator, quad, quantizer, tuner, visual, VCA

**Comment by david-c14** [comment]
The latest version of vcvrack is 1.1.6 (released November 2019)and includes significant api changes. Submarine free has been built against 1.1.6 and is not compatible with 1.1.5.

**Comment by aaronalt** [comment]
Thanks for the info. I know the latest version is 1.1.6, I run Rack v.1.1.5 due to compatibility issues with the audio I/O, and have a few patches with Submarine free modules that have never given me problems when using 1.1.5 until now.

**Comment by david-c14** [comment]
Interesting. If this problem is just with recent releases, previous builds are available from this github. You'd have to unsubscribe from Submarine in the Rack library and manually add the release, but that might keep you going.
