### ISSUE TITLE
Better labeling,  keywords [enhancement]

### ISSUE THREAD

**Issue by S0210** [david-c14/SubmarineFree#165]
Submarine is the best! :) I absolutely adore your modules. They're fantastic! 

But I always have hard time trying to find the right one in VCV rack library search.  If I type "XOR" for the searchbox I got some results but not yours. In general most of the searches excludes your modules without proper labelling.

I also have hard time studying an old patch and trying to see how I built it. Even if I right-click on a OG-202 or a XG-202 module I may struggle for another minute to figure out what that is for. 

Would you please consider improving the labelling of your modules somehow?

Cheers, A.

**Comment by david-c14** [comment]
Vcv rack library search is not very sophisticated.

There are a fixed and limited number of tags that can be put onto a module. XOR is not one of them.  I don't even think that gate is one of them.  So there's not much to be gained there.

Everything else the search does is just string matching on the name and the description. So short of stuffing the description with keywords it's a bit difficult.

**Comment by S0210** [comment]
Sad to hear that there's not much to do. But I already have a printed A4 sheet with my popular Submarine module names right at the monitor by now. :)

**Comment by ZwergNaseXXL** [comment]
Please reconsider. Besides the predefined tags, there are now keywords exactly for this search purpose. See https://vcvrack.com/manual/Manifest#modules-keywords.

**Comment by david-c14** [comment]
Agreed.
