### ISSUE TITLE
FF-110 irregular cycles

### ISSUE THREAD

**Issue by ZwergNaseXXL** [david-c14/SubmarineFree#169]
I just noticed that FF-110 is not a perfect binary counter but instead has some irregular cycles. It seems to be missing the occasional edge trigger. I haven't checked the other FF modules, but I guess they might have a similar issue. See screenshot:

![grafik](https://user-images.githubusercontent.com/16494722/141642131-0ac1cbc2-fce6-452f-b0b5-20d1ba304fcf.png)

**Comment by Petervos2018** [comment]
Maybe use a unipolar clock, sm clock out from Befaco is "bipolar" ?!

![afbeelding](https://user-images.githubusercontent.com/46076474/141647443-01a3e2c9-7b1f-4152-9e3d-81c5d0d3e66a.png)

**Comment by david-c14** [comment]
Have you configure the voltage range of the FF-110 to match the befaco output?

**Comment by ZwergNaseXXL** [comment]
Sorry for the late response. You're right, either switching off SM's "remove DC offset" (which makes it unipolar 0-10V) or adjusting FF's input range make it work as expected.

I guess the reason for sometimes triggering and sometimes not is this: Your modules are triggering at half the input range (mentioned somewhere in your manuals), which is 5V in this case, which is also the peak value of SM. But SM uses minBLEP to generate its signal, so it has some overshoot, which often (but not always) is enough to trigger the flip-flops.
