### ISSUE TITLE
Red Dot Loop/ 0.6.1 cannot open Submarine 

### ISSUE THREAD

**Issue by patman023** [david-c14/SubmarineFree#17]
Win10Home/0.6.1 Official

[0.647 warn] Failed to load library C:\Users\Pat\Documents/Rack/plugins/SubmarineFree/plugin.dll: code 127

**Comment by david-c14** [comment]
You need to upgrade your copy of VCVrack. Version 0.6.1 is now available

**Comment by patman023** [comment]
Reread the title? 0.6.1 already installed.

**Comment by david-c14** [comment]
Yes sorry, I deleted that response almost immediately, but you'd already been sent an email.

**Comment by patman023** [comment]
10-4

**Comment by david-c14** [comment]
I can't look into it right now. If it's causing a loop, unselect it in the plugin manager.  I'm afraid that Andrew has made it available again just a few hours ago, and I've not had a chance to test it myself yet.

**Comment by david-c14** [comment]
I've just downloaded the app 0.6.1 and selected SubmarineFree in the plugin manager (it was not selected).   It has downloaded and is running without any errors.   

Windows 10.

If this is still causing a problem, can you remove the SubmarineFree directory that's specified in the error message you are getting. Then try again. If you've made custom tunings, you might want to save them first.

**Comment by david-c14** [comment]
Please also see this issue on the Rack github

https://github.com/VCVRack/Rack/issues/1014

**Comment by patman023** [comment]
Resolved with a reinstall of 0.6.1.
