### ISSUE TITLE
Add CV inputs for octave multipliers in PO-204?

### ISSUE THREAD

**Issue by lnikj** [david-c14/SubmarineFree#18]
During producing an entry for the VCP-2 patch contest (https://www.youtube.com/watch?v=4MsecXwQxPo) I found myself wanting to 'play' the octave multipliers. This would have been made much easier if they had CV inputs. Would it be possible to add them?  Cheers (and thanks for your great modules!).

**Comment by david-c14** [comment]
I see no reason why not. I'll have to be careful not to break existing patches by adding more inputs.  I won't be doing in time for the end of the competition though. Sorry.

**Comment by lnikj** [comment]
That's great David. I certainly wasn't expecting you to shift the goal posts mid competition! Cheers.

**Comment by david-c14** [comment]
Will be in the 0.6.5 release.

**Comment by lnikj** [comment]
Magic. Thanks!
