### ISSUE TITLE
v2: Crash in XFX.cpp

### ISSUE THREAD

**Issue by cschol** [david-c14/SubmarineFree#182]
`link` is uninitialized and causes a crash in certain conditions (adding all modules to a patch at once).
`cv` could have similar problems and should be initialized also, but initializing `link` fixes the issue.

```
struct XF_LightKnob : LargeKnob<NarrowKnob<LightKnob>> {                                                  
    int cv;                                                                                          
    int link;                                                                                                    
    void step() override {                                                                            
[...] 
                      setEnabled(!module->inputs[cv].isConnected() && (module->params[link].getValue() < 0.5f));                      
```

**Comment by david-c14** [comment]
Thank you for finding this.

This is now fixed and will be available when I next do a release.

Have there been any actually reported crashes that implicate this?

**Comment by cschol** [comment]
We are not sure. Andrew found this crash with a test case of adding all modules of a brand to the Rack at once.

**Comment by david-c14** [comment]
Thanks. It's not theoretical then.
 I'll release sooner rather than later.
