### ISSUE TITLE
{whishlist] AO-101

### ISSUE THREAD

**Issue by S0210** [david-c14/SubmarineFree#187]
I know that the AO modules are to serve a greater purpose and they benefit from the multiple steps available in AO-106, AO-118, AO-136. However it clearly would be my first choice also for some quick calculation. 

Would you please consider rolling out a mini AO like this?

<img width="47" alt="image" src="https://user-images.githubusercontent.com/34127628/146668330-75a5c482-9b85-477e-9e7b-ac40feecf0ad.png">

**Comment by david-c14** [comment]
Thank you,  this has been added to version 2.0.4 and will be available when that version is released
