### ISSUE TITLE
AG-202 lower AND not working

### ISSUE THREAD

**Issue by jpnielsen** [david-c14/SubmarineFree#193]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/27916597/147922300-fecbc0f7-3785-4d03-b212-f481286814cc.png">

https://community.vcvrack.com/t/question-on-submarines-ag-202/15913

**Comment by S0210** [comment]
The bug may be present in other modules (like OG-202).

<img width="513" alt="image" src="https://user-images.githubusercontent.com/34127628/147922778-6b9a82b2-8840-400a-8bb6-f42521d4ce5e.png">

**Comment by jpnielsen** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/27916597/147923400-d0f53c12-2e42-48ab-9138-86c0ff5fc26a.png">

**Comment by david-c14** [comment]
Present on AG-202, OG-202 and XG-202

**Comment by S0210** [comment]
Thanks for the fix!
