### ISSUE TITLE
AO-101 potential bug (conditional)

### ISSUE THREAD

**Issue by firolightfog** [david-c14/SubmarineFree#200]
According to the settings if X input and Y input is the same then it should return C. But in the case below X is 0V, Y is 0V but the module returns 0V (instead of C that is 5V).

<img width="465" alt="image" src="https://user-images.githubusercontent.com/34127628/212907733-604b9d34-0cd9-4a03-a247-a6e329f0f7b0.png">

I'm uncertain if it's a bug or I incorrectly interpreted the rules.

Regards, Andras

**Comment by david-c14** [comment]
It's possible that my documentation is wrong. But from the picture it looks like.

If x =y then x else 0

I don't see C anywhere in the selected operator

**Comment by firolightfog** [comment]
My bad... I think I just though of one feature and selected another one. My apologies, A.
