### ISSUE TITLE
Segmentation fault upon insertion of OG 104 (or gates) #503

### ISSUE THREAD

**Issue by WouterSpekkink** [david-c14/SubmarineFree#24]
I am having a lot of issues with the OG 104 OR Gates on Debian 9. When I insert them, and sometimes when I use the context menu VCV rack often (but not always) crashes with a segmentation fault (illegal memory address accessed). It can create permanent problems with patches, causing immediate crashes on startup.

**Comment by david-c14** [comment]
OK, I'll look into it. 

I'm suspicious of my recent graphical changes, because the gates themselves have not changed recently.

**Comment by david-c14** [comment]
Issue found. Working on fix

**Comment by david-c14** [comment]
In the meantime, the OG-106 has the same functionality and does not suffer from the same bug. It does have a larger footprint.

**Comment by david-c14** [comment]
This is now fixed in version 0.6.8

Source code available from github.
Submitted to community for inclusion in the plugin manager (usually takes less than 1 week)
Windows build available from builds link.

**Comment by WouterSpekkink** [comment]
Awesome, thanks for the lightning fast fix!
