### ISSUE TITLE
Feature Request: TD-116 Text Display

### ISSUE THREAD

**Issue by InductiveOne** [david-c14/SubmarineFree#27]
I use this to label jacks on lots of modules to keep track of things. It would be helpful if the 'sync in' and 'sync out' jacks were at the bottom of the module and the text box was moved up closed to the bottom of the 'TD-116' label. I find many modules I would like to label have jacks higher than the top of the text field so it is a bit tough to get some things lined up.

Very minor issue, please put this way down your list of priorities if at all. Having the TF-101 to change text size is a huge help already, thanks for both!

![td-116featurerequest](https://user-images.githubusercontent.com/43386726/47193159-7bd7fe80-d31f-11e8-866d-a9986f076b45.jpg)

**Comment by david-c14** [comment]
I might do a different device, with separate moveable labels. That might work better, rather than having to fine tune the text size to try and match the pitch of the layout. 

But I'll certainly try to do something to improve this.

**Comment by espahbodb** [comment]
simple in/out with a label field and a #.#### format value viewer in the middle would do nicely.

**Comment by david-c14** [comment]
> simple in/out with a label field and a ##.#### format value viewer in the middle would do nicely.

I think you want a different device. If I understood your message, the ##.#### format value viewer would be to show the value of the input port.   But the ports on the TD-116 are torpedo modems, they don't have a useful value to display.

There are probably already other devices out there that do what you want.

**Comment by david-c14** [comment]
Version 1.0.4 now includes the TD-316. This has no torpedo ports and as a result has a text display area 20% larger than the TD-116.

You can still format the TD-316 (or the TD-116) because the TF-101 and new TF-102 text formatters also work as expanders.  They will format TD-xxx devices immediately to the left or right without the need for torpedo connections.
