### ISSUE TITLE
Modules build but grayed out in V1

### ISSUE THREAD

**Issue by tank-trax** [david-c14/SubmarineFree#30]
I am using Debian Stretch and am able to build both versions 0.6.2 and v1

SubmarineFree modules can be selected in Rack 0.6.2

![subfree 062 png](https://user-images.githubusercontent.com/41337033/59525902-8e520a00-8ea5-11e9-86a1-613eb3bcc09a.jpg)

but the SubmarineFree modules although show up in the list cannot be selected in v1

![subfree v1 png](https://user-images.githubusercontent.com/41337033/59525932-ac1f6f00-8ea5-11e9-9b5f-e67ef6b4c1b9.jpg)

**Comment by david-c14** [comment]
Submarine Free has not yet been ported to v1. That work us in progress, but until it is completed, the modules will not be available.

**Comment by david-c14** [comment]
Submarine Free modules have now been ported to v1 and are available in the plugin library
