### ISSUE TITLE
plugin.json issues

### ISSUE THREAD

**Issue by cschol** [david-c14/SubmarineFree#31]
The plugin manifest validation script found the following issues:

```
Validating SubmarineFree
Missing key: brand
Missing key: authorEmail
Missing key: pluginUrl
BB-120: invalid tags: SAMPLE
```

- Tags must adhere to tags defined in https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534.
- `pluginUrl` should be set to README.md of the Github repo.

**Comment by david-c14** [comment]
Plugin.json updated.  Head of master branch.

Thank you.
