### ISSUE TITLE
DN 112 No noise only min max

### ISSUE THREAD

**Issue by Petervos2018** [david-c14/SubmarineFree#33]
Hi David ,
It looks like the DN112 noise generator only outputs what you select in the right-click menu.
So if I choose 0V-5V I get 2 values 0V and 5V and nothing in between.
Same with the other settings.

Edit , I'm on Windows 7 rack V1

Greetings Peter.

**Comment by david-c14** [comment]
DN stands for digital noise. 

It produces a sequence of 1s and 0s at whatever the selectef logical voltage range. 

So from your description, its behaving exactly as it should.

**Comment by Petervos2018** [comment]
I thought as much but there was no manual where I could look this up.

Thanks 
Closing

**Comment by david-c14** [comment]
My apologies.

I've added a manual page.
