### ISSUE TITLE
EO-102 cont. / once switch won't stick

### ISSUE THREAD

**Issue by Petervos2018** [david-c14/SubmarineFree#34]
And when inserting a cv into channel A and choosing "RUN" it starts flipping between cont. and once.

Windows 7 VCV V1.

Greeting Peter.

**Comment by david-c14** [comment]
I found this while I was fixing the SS modules. A similar issue in the LA-108.

Both fixed and waiting to get this to the plugin manager.

**Comment by david-c14** [comment]
Fixed in v1.0.1

Now available in the plugin manager
