### ISSUE TITLE
WM-101 - option to color a specific wire a specific color

### ISSUE THREAD

**Issue by david-c14** [david-c14/SubmarineFree#37]
If possible add a menu option to a color on the list such that if selected, that color is highlighted, and the next wire added or moved will be colored using that selected color.

The option should be cancellable, and it should auto-cancel after the wire is recolored

**Comment by Coirt** [comment]
Hi David, a couple of things you might be able to enhance also on WM-101:

Read `settings-v1` for current colours, if the list is still on the 4 default colours use your defaults, if it has been changed manually read the changes and set your defaults to these colours.

If that is not possible then a text field to paste colours into or at the very least a display to show the current RGB values for the current edit colour in the choice area. `hex` code or the `rgb` value or both would be nice, something just to show the values.

There should be a way to loop through the display string and separate and append the index `[0] + [1], [2] + [3]` etc... into the valid hex code.

**Comment by david-c14** [comment]
When you first load it and it creates the defaults, it uses the colors that Rack has already loaded from settings-v1.  These it checks, and then it loads the remaining WM-101 defaults and leaves them unchecked.  But it doesn't reread the colors from settings-v1 after the first time that you have made any changes in the WM-101.

It puts the hex colors at the top of the right-click menu, but it doesn't currently show that dynamically while you are changing colors using the sliders.  I wanted the color selection to be more of an exploratory experience, which is why I put the colored gradients behind them as they are.

But I will consider putting in one or other of your suggestions, so that users can more easily choose specific hex codes.

In the meantime you can edit the settings file yourself it's in <RackDir>/SubmarineFree/WM-101.json  if you want to put hex colors in to the wire manager.

**Comment by Coirt** [comment]
Ah, didn't realise it had a json. Great!

**Comment by david-c14** [comment]
That's a possibility.  By all means add new issues for things like this.

**Comment by david-c14** [comment]
Text field to enter hex codes is in v 1.0.4

**Comment by david-c14** [comment]
Ability to color a single wire a specific color is in v 1.0.4

Use the context menu for a wire color, or double click on the wire color to enable the mode.  A cancel button allows for cancelling the mode, otherwise it autocancels when it colors the next wire you add, OR the next wire you move.
