### ISSUE TITLE
Issue with opacity

### ISSUE THREAD

**Issue by Jairodallos** [david-c14/SubmarineFree#38]
Hello,
please see this video:

https://youtu.be/g8OfaBUdeMY

i´m having trouble with opacity and may be your module WM-101

please read the feed in https://github.com/VCVRack/Rack/issues/1502

Regards

**Comment by david-c14** [comment]
I'll look into it.

First thing for you to do is to put a WM-101 into your rack.
Make sure that the highlighting is off (in the WM-101 settings menu)
Then you can remove the WM-101 from the rack.


Can I ask if you had a crash with the WM-101 in the rack?

**Comment by Jairodallos** [comment]
Hello
No

In my case no crash has happened.

Only this issue with random opacity reactions in rack

**Comment by david-c14** [comment]
My best guess at this point is that the version of the WM-101 loaded into the module browser is altering the opacity.  It shouldn't.  It shouldn't be doing anything unless it's actually put into the rack. But there might well be a bug there. I'll investigate further and if necessary issue a patch ASAP.

**Comment by david-c14** [comment]
This is fixed in version 1.0.3 which should be released shortly.
