### ISSUE TITLE
FR: WM-101 function keys to select/deselect colors

### ISSUE THREAD

**Issue by Coirt** [david-c14/SubmarineFree#39]
As mentioned in #37 the ability to select `cableColor` with function keys `f2 -f12` would be useful.

I'd probably avoid mapping keys too close to backspace but with `undo` there is a less risk of a mis-presses, deleting a module.

**Comment by david-c14** [comment]
Given that you have to bring the mouse over the module to use the keys, and then you need to move the mouse again to make new wires. I'm not convinced that this is a useful enhancement
