### ISSUE TITLE
TD-202 - Text difficult to erase

### ISSUE THREAD

**Issue by nesdnuma** [david-c14/SubmarineFree#40]
Hello,

The TD-202 is a nice module. However it is a bit hard to set cursor at a specific place to edit text, specifically at the end of the text when one wants to erase everything.

Cheers.

**Comment by david-c14** [comment]
Agreed.

This is an outstanding issue.   I fixed it in v0.6 of rack,  but changes to the API mean that it needs fixing differently in v1.0

I'm hoping to fix it soon.

The best way to deal with it at the moment is to click near the top to get the cursor into the text, and then use left and right arrow keys to get where you want.

**Comment by nesdnuma** [comment]
Thank you.

**Comment by david-c14** [comment]
Fixed in v1.0.4

Should be released soon
