### ISSUE TITLE
WM-101 Add multiple color sets

### ISSUE THREAD

**Issue by david-c14** [david-c14/SubmarineFree#41]
- Add the ability to save a selection of colors as a preset. 
- Name that preset.
- Switch to preset arrangements quickly.
- Display the presets on a scrolling window (like the wire colors window).
- Each item to show the name of the preset, and a rainbow strip displaying the colors in the preset.
- ~~Potentially add the presets to the burger menu as a submenu. Again with rainbow strip.~~ Not doing that.

Note that switching to a preset would necessarily lose the current selection of colors. ~~I could implement a warning when you do, to which you could say 'don't show me this again'.~~ Not doing that, it would slow the user down too much. Undo is implemented.

**Comment by teknico** [comment]
As for quickly switching to a preset, even though global shortcuts are not available, keyboard shortcuts while the mouse hovers on the module would be welcome. The event is `HoverKey`, here is a usage [example](https://github.com/VCVRack/VCV-Prototype/commit/668ead6046bdbf2004d20636f07dd81a158c463c#diff-e87d1fa4437e164531bcdc587e6b0926R436).

**Comment by david-c14** [comment]
I'll consider it, but I'm still not convinced that there is a strong use case.

**Comment by teknico** [comment]
The use case is being able to quickly access a color, without having to cycle through all of them (I have 12), or having to select and unselect colors all the time by clicking on them, which is what I currently do. If I could count the overall number of clicks per module, WM-101 would leave all others in the dust. :-)

Presets would allow me to group colors in, say, four groups of three and more quickly set WMW-101 to one of those groups. Or I could even define 12 presets, each with just one color, and access them with Ctrl-F1...Ctrl-F12, for instance. :-)

**Comment by david-c14** [comment]
Ok, that's persuasive.

I'll see what I can do.

**Comment by david-c14** [comment]
Added Ctrl-F1 through to Ctrl-F25 for the first 25 color collections.
Will see if it's feasible to add Shift-F1 - Shift-F25 for the tick boxes on individual colors.

I know that most computers have only 12 function keys, but there are 25 assigned scan-codes. Some keyboards have more than 12, and some device drivers let you map things like gamepad buttons, so there's no harm in coding it up that way.  If you don't have F-13 you can't press F-13 - tough :)

**Comment by david-c14** [comment]
I think I need to add 'Move Up' and 'Move Down' to the collection items. I wasn't going to bother, but if you want to ensure that your favorite collections are assigned to Function keys you can remember, I think there is a strong use case, and it's not a big piece of work.

**Comment by teknico** [comment]
Yoohoo! Thank you so much for this! I can feel the time for another donation getting closer... ;-)
