### ISSUE TITLE
LA-108 Increase maximum time-base and module width

### ISSUE THREAD

**Issue by ContemporaryInsanity** [david-c14/SubmarineFree#42]
Please could we have a longer time selection available, would be great for visualising long envelopes, very slow LFO's etc.  Preferably up to several minutes.  Would also be really nice if module width could be altered by dragging like with JW Full Scope.

**Comment by david-c14** [comment]
I can do a longer time selection. But the LA-108 is design for digital signals. You might be better with the EO-102 for looking at envelopes. Its optimised for that.

**Comment by david-c14** [comment]
I still intend to do a hi-res storage scope. That will have a wider display and longer time base. Its not high on my list of priorities though.

**Comment by david-c14** [comment]
Several minute time bases either require very large buffers, or they lose an enormous amount of detail. Simply extending a fundamental scope to a long time base risks the results being overwhelmed by aliasing.

**Comment by ContemporaryInsanity** [comment]
I just find the LA-108 handy for this purpose as it has eight channels and minimal CPU hit.  For visualising slower stuff I'm currently using wiqid full scope, that gives me up to thirty seconds of two channels, a minute or more with more channels would be useful.

**Comment by david-c14** [comment]
version 1.1.7 extends the maximum time-base to 128 seconds.    The physical module size will not be increased.
