### ISSUE TITLE
AO-1xx Conditional Algorithms

### ISSUE THREAD

**Issue by ZwergNaseXXL** [david-c14/SubmarineFree#52]
The conditional algorithms are somewhat redundant, while others are missing. For instance, there's 
`if Y>C↣Y/X | (y > c) ? y : x` and there's also `if C<Y↣Y/X | (c < y) ? y : x`, which is the same, but there's no `if Y>C↣X/Y | (y > c) ? x : y`.

Are you sure that's what you meant to do? 
See https://github.com/david-c14/SubmarineFree/blob/master/manual/AO-list.md.

**Comment by david-c14** [comment]
Probably not :( but its too late to fix it now.

**Comment by ZwergNaseXXL** [comment]
Why too late? You mean because people might be using the redundant entries in their patches? 
You could leave them where they are and just append the missing ones to the end of the list, although that is kinda ugly. 
Or just release a new device with the fixes (AO-1xx.2 or smth) and leave the buggy one as a legacy device.
Or just do it the proper way and let people cope with it. :)

**Comment by david-c14** [comment]
Possible candidate for a replacement series of devices. But not going to risk a breaking change on this one.
