### ISSUE TITLE
Win build error

### ISSUE THREAD

**Issue by MarcBoule** [david-c14/SubmarineFree#53]
Hi David, I'm getting an error during the build process. I'm using Windows 10, and the latest commit from your v1 branch:

```
src/DO1.cpp: In lambda function:
src/DO1.cpp:382:12: error: 'this' was not captured for this lambda function
     return this->getGateText(knob);
            ^~~~
```

**Comment by david-c14** [comment]
The v1 branch is not a release branch, it's currently the primary development branch. So I make no guarantees as to it's stability at any stage.

Anyway if you want to fix it temporarily I think this will work:
on line 314 replace:
```
		knob->getText = [&knob]()->std::string {
```
with:
```
		knob->getText = [=]()->std::string {
```
