### ISSUE TITLE
TD-316 Resizable

### ISSUE THREAD

**Issue by Telerex** [david-c14/SubmarineFree#55]
As much as I love your text display modules, there are times when the size of them doesn't line up with what ever module I am trying to label.
Could you make a text display that was resizable like the VCV blank panel or the Computerscare custom blank?
 Either way, thanks for a great set of modules.

**Comment by Telerex** [comment]
Thank you for TD-410 #106  . Already making great use of it. Can I be cheeky and say, something similar for vertical text would be nice. Again thanks.

**Comment by david-c14** [comment]
I'm not sure what you mean? Similar in what way?

**Comment by Telerex** [comment]
![TD-316v](https://user-images.githubusercontent.com/55559146/79000002-b9e46600-7b43-11ea-8b55-4fb061ad231a.jpg)
Something like this and even add vertical text to TD-202 or the ability to swap its orientation would be lovely.

**Comment by david-c14** [comment]
I'm not sure what is the use case for this. Is it that much more useful than several td-202 next to each other?

**Comment by Telerex** [comment]
![pin matrix](https://user-images.githubusercontent.com/55559146/79005473-d20db280-7b4e-11ea-8dfb-be0ba5ee3fbf.JPG)
It's just a wish on my part, but it would help with the labelling of matrix mixers (of which there were 9 in VCV, at last count). 
As you can see, things don't quite line up. Plus it could aid in labelling any mixer channels.
It's also one more option for people and choice is always good, is it not?
Either way thanks for all you've done so far, great work.
