### ISSUE TITLE
DO modules see no in and produce no out on MacOS

### ISSUE THREAD

**Issue by fractalgee** [david-c14/SubmarineFree#58]
Plugin version 1.1.0
Rack 1.1.6
MacOS X 10.11.6

The DO modules seem to not work at all in MacOS X. 

I have Clocked (Impromptu) with main clock and 3 divided/multiplied clock outs into the 4 ins at the top. None of the DO modules see any input being connected, but the panel seems non-functional, in that no dots can be clicked, it sticks with all channels saying N/C and no obvious way to get anything to happen. I have to conclude that the Mac version seems broken.

If there is anything else I can give you to see what might be going on then let me know, please.

**Comment by david-c14** [comment]
I can't think of anything else you can give me. When you say that you can't click on the dots. You need to click and drag up and down, like a knob; is that what you are doing?

**Comment by fractalgee** [comment]
Tried, I can manually set the buttons on left of each channel manually (right click to enter value) to any of the incoming gates, after that nothing else seems to work. Dragging/turning/clicking, all I can get going is map incoming to the knobs/buttons,whatever they are on the left of each channel manually....

**Comment by fractalgee** [comment]
![DO_NoWorky](https://user-images.githubusercontent.com/12473856/69904116-f1c3eb80-13a2-11ea-84fa-a42f44c86726.png)

That is as far as I can get, no output.....

**Comment by david-c14** [comment]
From the picture it looks as though you've not connected the output ports to the output of any gates. All the output port dots (along the bottom) look to be black. Connect them to the pink/purple gate outputs

**Comment by fractalgee** [comment]
Aha, some vey unintuitive way to get this to emit gates. Got it working
now, but I would have sort of expected the outs to inherit from the results
from the channels, but guess that  it would need 5 ins and 5 outs then for
the 105 version, and many more for the bigger siblings.....

**Comment by david-c14** [comment]
I'm glad its working. I'll try to improve the manual.

**Comment by spectromas** [comment]
I found it very intuitive. I don't understand why you need to right click to do things, you should be able to do it all from the panel. It wouldn't make sense for the output node of the logic to be automatically routed to the output ports as the beauty of this modules is that the logic sections can be chained and fed to one another.

**Comment by fractalgee** [comment]
well, no idea how to do it from the panel for the outputs, no way I can
find, can just right click the out little grey button and set it to
channel 6 for OP 1, 7 for 2 and so on on the DO-105 for example. I found
the assignment can be modulated via the stoermelder micromap module but
what voltage I need is fiddly to modulate through the 5  possible ones, and
even tricker for the bigger siblings so a guide what voltage calculation
one should use would be good as well....  Also, some edification of how to
not have to right click on all the dots for the left of the OPs and for the
outs to get the values needed assigned, as they can't be dragged or
anything else, would be very much a good idea methinks

**Comment by david-c14** [comment]
I've never use the stoermelder micromap, so I don't know how it represents things. The connections and gate are not measured in volts, so I don't know how they map.  For the dots, the numbered values should be 0-5 for the input ports, then 6 is the output of the first gate, 7 the next gate etc.  The gates are just numbered from 0 upwards.

**Comment by fractalgee** [comment]
Yes, that much I worked out, so all good. Might be good to be able to set
the dots via drag up and down as well like the OP choice on the right side
dot. Would make this a wee bit easier to get head around.  Maybe some
expander that lets me modulate the output port choice that works with all 3
DO modules might be sweet. Those dots are hard to hit with the mouse so not
settable during performance which is a bit of a bummer. Great modules, but
could use a wee bit of interaction enhancement.

**Comment by david-c14** [comment]
The left dots and the bottom dots should all respond to dragging up and down. But they do go at different speeds because there are fewer options near the top of the device.  I hope to make them more consistent.

**Comment by fractalgee** [comment]
Aha, the different sensitivity is the issue here, cranked up mouse
sensitivity a tad and now it sorta works. Now to find out how to modulate
these and we are in generative heaven ;) XPanda might me a good thing still
for modulation ease :) Sort of, if I have 5 choices divide 10 volts by 5 so
each choice is 2 volts apart kinda thing given you must know already how
many choices there are....  anyhow, just throwing out ideas....

Thanks for patience with befuddled me. I can usually figure stuff out
pretty well, this was the first thing since Nysthi Squonk that threw me off
completely and took some explaining for me to get head around....

Anyhow, thanks for the modules, always something unexpectedly nice to find
in that collection, and so logically named too :)

go well

**Comment by david-c14** [comment]
I am sorry you found it troublesome. Feedback has been mixed, some people found it intuitive, but you are not the only one who didn't. 

It seems odd for automation tools to work in terms of volts for the parameters. That really confuses me, because parameters have arbitrary ranges, whereas inputs and outputs have traditional voltage ranges. 

I didn't design it with performance in mind. I might be able to add a preset option, so you could save several configurations and switch between them with a single click, or maybe a keypress.

**Comment by fractalgee** [comment]
well, that would already enhance the usability, if one could save and
switch saved preset stuff.
