### ISSUE TITLE
WM-101 could save names and descriptions for colors and color sets

### ISSUE THREAD

**Issue by jimallman** [david-c14/SubmarineFree#80]
I'd love to see this, personally. It would also facilitate sharing [color conventions like these](https://community.vcvrack.com/t/choosing-cable-colors-in-vcv-1-0/4155). If you like the idea, I can probably take a swing at this and submit a pull request.

**Comment by david-c14** [comment]
:thumbsup:

I'll try to tackle this within the next week. If I don't make it, you're more than welcome to submit a PR.

**Comment by jimallman** [comment]
This looks like a good first Rack project for me, so I'm giving it a shot this weekend.

**Comment by jimallman** [comment]
I've started a pull request against branch `master` (probably not correct). I'm taking an incremental approach, so I'll keep pushing commits to this as follows:

  - [x] add useful named color sets (conventions) on first install
  - [ ] **Add New Color** should offer a name field
  - [ ] **Edit [existing color]** should do the same
  - [ ] color name should appear in 
    - [ ] tooltips (over a color)
    - [ ] on mouseover (over a color)
    - [ ] on mouseover (of color chip) in color-set list 
      - [ ] Use taller color chips for this purpose?
  - [ ] **Save As Collection** should offer a color-SET name field
  - [ ] save/load this information in `WM-101.json` file
  - [ ] offer some kind of add/merge of shared color sets, for existing users?

**Comment by david-c14** [comment]
I use a branch methodology called gitflow. So I won't be accepting a PR directly into master. I'll move your PR to *develop* which would be the appropriate target.

I have a branch in progress which does the saving of collections, and which will shortly do the loading. 

I will certainly accept some of these proposals, but I need to think about others. It might be better if you could submit separate PRs for the work. That would require you to separate each stage into its own branch. I appreciate that might not always be practical, so its not a hard and fast rule.

I appreciate your suggestions and your help. This is a great help. Thank you

**Comment by jimallman** [comment]
> I'll move your PR to develop which would be the appropriate target.

Sounds good. I'll keep this in mind.

> I will certainly accept some of these proposals, but I need to think about others. It might be better if you could submit separate PRs for the work.

Most of the upcoming changes are pretty interdependent, so I'm not sure how practical that will be. I can break them up, but I'm inclined to keep them bundled together and revert any changes that you don't want.

As a general note, I'm pretty new to both C++ and the Rack APIs. Feel free to point out where I'm Doing It Wrong or missing helpful built-in features. :bowtie:

**Comment by david-c14** [comment]
I remain to be convinced of the utility of naming individual colors. But I'm not completely dismissing the idea... Convince me.

My objections are that the tool is intended to let a rack user have the colors they want. If they've chosen a color scheme, surely they know what they intend to use those colors for.  I'm not convinced that there is a strong need for a mnemonic.

**Comment by jimallman** [comment]
Fair enough! As a Rack newbie, I've been trying out different color conventions, and I'm struck by how Omri needs a blank plate just to label his.
![Screen Shot 2020-03-21 at 10 46 49 AM](https://user-images.githubusercontent.com/446375/77228967-4b724080-6b61-11ea-8282-1106550dc9b0.png)

I'd love to see (optional) descriptions directly in WM-101 (see crude mockup below). This would make it easier to try others' color conventions, and easier for other users to interpret the wire colors used in a patch.
![wire-color-names-mockup](https://user-images.githubusercontent.com/446375/77229218-ed465d00-6b62-11ea-973c-c3afc660ca28.png)

**Comment by david-c14** [comment]
Omri doesn't need a plate for this. He knows what he's doing.   

Viewers of his videos asked for a plate so that they could be reminded of what he meant by his convention.

**Comment by david-c14** [comment]
A separate blank plate to do this job might make a fine project.  It could load and save the same format as the wiremanager now does.

**Comment by jimallman** [comment]
> That would be much easier to read in someones video that the small text on the WM itself.

Hm, point taken. I guess my use case is different -- someone browsing collections to use in their own patches.

**Comment by jimallman** [comment]
> A separate blank plate to do this job might make a fine project. It could load and save the same format as the wiremanager now does.

Maybe this could be a third view of WM-101: default, minimized, and "billboard"?

**Comment by jimallman** [comment]
Here's a mockup of the third "billboard" view described above (for use on YouTube and the like):
![wire-color-billboard-mockup](https://user-images.githubusercontent.com/446375/77243164-5bc80100-6bdd-11ea-9569-fff6282463b2.png)
Note the arrow at upper left to return to the default view. Here's that view with arrows to switch to minimized view (left) and to the billboard view (right):
![wire-color-names-mockup-2](https://user-images.githubusercontent.com/446375/77243230-1e17a800-6bde-11ea-8ee3-f2cc57e01dfe.png)

**Comment by david-c14** [comment]
OK. The billboard is an option.  I think I'm happy with an optional name for each color. I'm less happy with prompting automatically for a name. And I don't like displaying the names above the wires.

I like...
- an optional name for a colour
- a name editor on the context menu, as with collections
- a tooltip on the colour
- a tooltip on the colour chips with taller chips if necessary.
- tooltip should not appear if name is blank.
- I'd still prefer a separate billboard module, but it could automatically respond to a wire manager. Having it built in to the wire manager doesn't work so well if you share it in a patch, because the wire settings are not part of the patch.

**Comment by david-c14** [comment]
No sarcasm intended. You are perfectly free to fork this open source project and make your own wire manager.

**Comment by jimallman** [comment]
Thanks for your detailed feedback! Your approach hides the color names a bit more than I'd like, but it would make them available for anyone who cares.

Are you OK with adopting the required changes to JSON structure? We'd need to add a 'name' or 'label' property to each of the current colors: 
```json
  "colors": [
    {
      "color": "#ff0000",
      "selected": 0.0,
      "label": "foo"
    },
```
... and the more radical change of hex-strings to objects for collection colors, from this:
```json
  "collections": [
    {
      "name": "Modular Fungi",
      "colors": [
        "#c9184700",
        "#0986ad00",
        "#c9b70e00",
        "#0c8e1500"
      ]
    },
```
...to this:
```json
  "collections": [
    {
      "name": "Modular Fungi",
      "colors": [
        {"value": "#c9184700", "label": "Audio"},
        {"value": "#0986ad00", "label": "Clk/Trig/Gate"},
        {"value": "#c9b70e00", "label": "V/Octave"},
        {"value": "#0c8e1500", "label": "Modulation"}
      ]
    },
```
This would require some dancing around the old and new JSON structures, so there might be ripples elsewhere in your code. Maybe not worth the hassle...?

**Comment by jimallman** [comment]
> You are perfectly free to fork this open source project and make your own wire manager.

Understood, but if we don't see eye to eye, I'd rather move on to other projects. Your module clearly fills the basic need, and mine would just add to the clutter of existing modules unless there's a more compelling difference. (Named colors aren't much use for just one person, they're more of a community thing.)

Thanks again for all your patient responses. This has been a good learning experience, and I will continue hacking on VCV Rack regardless.

**Comment by david-c14** [comment]
I'm happy with adding name to the color in the json.  An alternative suggestion for the color collections would be to have an array of colours, and an array of names, rather than an array of new structures.  That would not be a breaking change.

**Comment by jimallman** [comment]
> An alternative suggestion for the color collections would be to have an array of colours, and an array of names, rather than an array of new structures. That would not be a breaking change.

True. In my experience, this approach can lead to bugs if colors and names aren't managed properly in tandem, but it's probably worth it in this case. I'll move forward with this approach.

**Comment by david-c14** [comment]
FYI: I found a memory leak.

Because you are not adding the Label edit field except when the edit panel is visible, and then removing it when the panel becomes invisible.   It may not be attached (as a child) when the module is deleted.  If not, it will not be deleted at all. 

I need to write some code to ensure that when the edit panel is disposed, that the edit field is disposed if it was not already attached to the panel.

**Comment by jimallman** [comment]
Thanks for catching this. I suppose we could also recreate this field each time the panel is used. I'm genuinely surprised there isn't some way to disable a text field so that it doesn't capture all keyboard events for awhile.

On a related note, it seems I can crash Rack (on Mac, anyway) by editing a label, then hitting the Return key. The Save button works normally, but the Return key results in a crash and this log entry:
```log
[19.340 info src/settings.cpp:189] Saving settings /Users/jima/Documents/Rack/settings-v1.json
[25.683 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
14: 1   Rack                                0x000000010f4c63cd _ZL18fatalSignalHandleri + 45
13: 2   libsystem_platform.dylib            0x00007fff6c8e4b5d _sigtramp + 29
12: 3   ???                                 0x0000000000000000 0x0 + 0
11: 4   plugin.dylib                        0x00000000159d7ce8 _ZN15EventParamField11onSelectKeyERKN4rack5event9SelectKeyE + 200
10: 5   Rack                                0x000000010f4c0f01 _ZN4rack5event5State9handleKeyENS_4math3VecEiiii + 305
9: 6   Rack                                0x000000010f4dd8f0 _ZN4rackL11keyCallbackEP10GLFWwindowiiii + 64
8: 7   Rack                                0x000000010f59c60e -[GLFWContentView keyDown:] + 174
7: 8   AppKit                              0x00007fff3ded4367 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6840
6: 9   AppKit                              0x00007fff3ded2667 -[NSWindow(NSEventRouting) sendEvent:] + 478
5: 10  AppKit                              0x00007fff3dd72889 -[NSApplication(NSEvent) sendEvent:] + 2953
4: 11  Rack                                0x000000010f59eaad _glfwPlatformPollEvents + 109
3: 12  Rack                                0x000000010f4dde0b _ZN4rack6Window3runEv + 139
2: 13  Rack                                0x000000010f4c5efa main + 1434
1: 14  Rack                                0x000000010f45f034 start + 52
0: 15  ???                                 0x0000000000000001 0x0 + 1
```
The reference here to a _delayed_ event makes me think this might be trying to capture the text field's value after it has been removed. Hopefully the fix you're planning will address this as well.

**Comment by david-c14** [comment]
The EventParamField should have a handler for when you click on it. I don't think you've supplied a handler.

**Comment by david-c14** [comment]
Found and fixed.

The EventParamField is designed to be part of a menu.  When you press enter, it closes it's parent menu.  It was crashing because it doesn't have a menu ancestor
