### ISSUE TITLE
Wire Manager crash

### ISSUE THREAD

**Issue by ContemporaryInsanity** [david-c14/SubmarineFree#92]
On hitting enter after typing a 'Color label'.  Consistently crashes.  Running under linux.

10: ./Rack(+0x1f63b5) [0x560952fce3b5]
9: /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f941ede3f20]
8: ./Rack(_ZN4rack6widget6Widget13requestDeleteEv+0) [0x560953019096]
7: /home/ewen/.Rack/plugins-v1/SubmarineFree/plugin.so(_ZN15EventParamField11onSelectKeyERKN4rack5event9SelectKeyE+0x14f) [0x7f93ec35fb59]
6: ./Rack(_ZN4rack5event5State9handleKeyENS_4math3VecEiiii+0x26e) [0x560952f9e8ae]
5: ./Rack(+0x1efe4d) [0x560952fc7e4d]
4: ./Rack(_glfwPlatformPollEvents+0x299) [0x560953064aec]
3: ./Rack(_ZN4rack6Window3runEv+0x8e) [0x560952fc80b0]
2: ./Rack(main+0x4cc) [0x560952f3e8ec]
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f941edc6b97]
0: ./Rack(_start+0x2a) [0x560952f4389a]

**Comment by david-c14** [comment]
Thanks.
Found and fixed
